#!/bin/sh

BUILD_DIR = "build"
DEB_DIR = "$BUILD_DIR"/php7.2-zstd_1.4.1-1

rm -rf "$DEB_DIR"
mkdir "$DEB_DIR"
cp -a DEBIAN "$DEB_DIR"/
mkdir -p "$DEB_DIR"/etc/php/7.2/mods-available
cp -a zstd.ini "$DEB_DIR"/etc/php/7.2/mods-available/
mkdir -p "$DEB_DIR"/usr/lib/php/20170718
cp -a ../modules/zstd.so "$DEB_DIR"/usr/lib/php/20170718/
chown -R root:root "$DEB_DIR"
chmod a=r,u=rw "$DEB_DIR"/usr/lib/php/20170718/*
chmod a=r,u=rw "$DEB_DIR"/etc/php/7.2/mods-available/*
dpkg-deb --build "$DEB_DIR"
